"""Raw event strings (common vendor names the gateway maps to canonical metric keys)."""

APP_LOGIN = "app.login"
APP_SESSION_END = "app.session.end"
APP_FEATURE_USED = "app.feature.used"
BILLING_SEATS_USED = "billing.seats.used"
BILLING_SEATS_PURCHASED = "billing.seats.purchased"
APP_USER_ACTIVE = "app.user.active"
APP_ONBOARDING_COMPLETED = "app.onboarding.completed"
SUPPORT_TICKET_OPENED = "support.ticket.opened"
SUPPORT_TICKET_RESOLVED = "support.ticket.resolved"
SUPPORT_TICKET_NEGATIVE = "support.ticket.negative"
SURVEY_NPS = "survey.nps"
SURVEY_CSAT = "survey.csat"
BILLING_SEAT_EXPANDED = "billing.seat.expanded"
BILLING_PLAN_UPGRADED = "billing.plan.upgraded"
GROWTH_REFERRAL = "growth.referral"

# Tier-C vendor aliases
ORDER_PLACED = "order.placed"
ORDER_COMPLETED = "order.completed"
CHECKOUT_COMPLETED = "checkout.completed"
CART_ABANDONED = "cart.abandoned"
PRODUCT_VIEWED = "product.viewed"
ORDER_REFUNDED = "order.refunded"
CARD_TRANSACTION = "card.transaction"
BILL_PAID = "bill.paid"
PAYMENT_DECLINED = "payment.declined"
SUBSCRIPTION_SKIPPED = "subscription.skipped"
PAYMENT_FAILED = "payment.failed"
DELIVERY_ISSUE = "delivery.issue"
APP_OPEN = "app.open"
IAP_PURCHASE = "iap.purchase"
PAYWALL_VIEW = "paywall.view"
TRANSACTION_COMPLETED = "transaction.completed"
SEARCH_PERFORMED = "search.performed"
LISTING_CREATED = "listing.created"
